// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArLBLZPJGkCn1tEqxBtULvd7U_5WMDzL0',
    appId: '1:348883026139:web:c5792b3b622713ecb7ccfe',
    messagingSenderId: '348883026139',
    projectId: 'prac-1e4c7',
    authDomain: 'prac-1e4c7.firebaseapp.com',
    storageBucket: 'prac-1e4c7.appspot.com',
    measurementId: 'G-3QBJS7Y277',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy2V_1RxP8cc7HIB_zZBgXzlCRPs2emqw',
    appId: '1:348883026139:android:2e551953e91470d1b7ccfe',
    messagingSenderId: '348883026139',
    projectId: 'prac-1e4c7',
    storageBucket: 'prac-1e4c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7_PG00zZI3MrGH-8XWuIdmsUAzfF1Hj8',
    appId: '1:348883026139:ios:d201b026bf3a82cab7ccfe',
    messagingSenderId: '348883026139',
    projectId: 'prac-1e4c7',
    storageBucket: 'prac-1e4c7.appspot.com',
    iosBundleId: 'com.firebolt.prac',
  );
}
